# FindPortAudio.cmake
find_path(PORTAUDIO_INCLUDE_DIR portaudio.h)
find_library(PORTAUDIO_LIBRARY NAMES portaudio)

if(PORTAUDIO_INCLUDE_DIR AND PORTAUDIO_LIBRARY)
    set(PORTAUDIO_FOUND TRUE)
else()
    set(PORTAUDIO_FOUND FALSE)
endif()

mark_as_advanced(PORTAUDIO_INCLUDE_DIR PORTAUDIO_LIBRARY)

set(PORTAUDIO_LIBRARIES ${PORTAUDIO_LIBRARY})
set(PORTAUDIO_INCLUDE_DIRS ${PORTAUDIO_INCLUDE_DIR})